server:
  port: 8001
# mybatis配置
mybatis:
  type-aliases-package: com.yrp.entity
  config-location: classpath:mybatis/mybatis-com.yrp.config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  application:
    name: provider-dept
# 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
# actuator
info:
  app.name: yrp
  company.name: www.yrp.com
